import { Heading, Stack, VStack, Text, Button } from '@chakra-ui/react'
import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>NEXT JS API TESTING</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <VStack>
        <Heading>
          Welcome to NextJS API TESTING
        </Heading>
              <Stack direction="row">
                  <Text>NextJS Api testing is currently being used to test GraphQL with Strapi (SKR API)</Text>
              </Stack>
              <Link href='/testing'>
                  <Button>Head to testing page</Button>
              </Link>
      </VStack>
    </div>
  )
}
